git-issue.sc.mov: youtube-script.sh /cygdrive/r
	$(MOOC)/textanimate/makemovie.sh -s youtube-script.sh git-issue

# Create RAM disk; see http://www.ltr-data.se/opencode.html/#ImDisk
/cygdrive/r:
	imdisk -a -t vm -m R: -s 2G -p "/fs:ntfs /q /y"

